**The typical modules we need for Data science and Machine Learning.**

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt

Let's read the input csv files. We want to see the header and some initial data.

In [2]:
df = pd.read_csv("/kaggle/input/best-selling-consoles-and-their-best-selling-games/best-selling game consoles and their best-selling games.csv")
df.head()

,Console,Most Sold Game,Year of Release (Game),Units Sold (in millions),Extra Information
0,PlayStation 2,Grand Theft Auto: San Andreas,2004,17.33,NaN
1,Nintendo DS,Nintendogs,2005,24.67,NaN
2,Nintendo Switch,Mario Kart 8 Deluxe,2017,52.00,NaN
3,Game Boy,Tetris,1989,35.00,NaN
4,Game Boy Color,Pokemon Gold/Silver/Crystal (1999-2000),1999,23.10,NaN

In [3]:
# This gives us all the column headers
df.columns

Index(['Console', 'Most Sold Game', 'Year of Release (Game)',
       'Units Sold (in millions)', 'Extra Information'],
      dtype='object')

In [4]:
# How many records (i.e. rows) do we have?
len(df['Console'])

51

In [5]:
# The 'Extra Information' column is useless information here. So I am going to delete it.
df = df.drop(columns=['Extra Information'])
df.head()

,Console,Most Sold Game,Year of Release (Game),Units Sold (in millions)
0,PlayStation 2,Grand Theft Auto: San Andreas,2004,17.33
1,Nintendo DS,Nintendogs,2005,24.67
2,Nintendo Switch,Mario Kart 8 Deluxe,2017,52.00
3,Game Boy,Tetris,1989,35.00
4,Game Boy Color,Pokemon Gold/Silver/Crystal (1999-2000),1999,23.10

In [6]:
# let's find the game that sold the most irrespective of year or gaming platform.
print(f"The maximum number of units sold is ",df['Units Sold (in millions)'].max())

The maximum number of units sold is  82.88

In [7]:
print(f"The row index of the game with the max number of units sold is ",df['Units Sold (in millions)'].idxmax())

The row index of the game with the max number of units sold is  7

In [8]:
# The actual row data
df.iloc[[7]]

  Console Most Sold Game  Year of Release (Game)  Units Sold (in millions)
7     Wii     Wii Sports                    2006                     82.88

Looks like 'Wii Sports' sold 82.888 million units. It was made for the Nintendo Wii platform.

In [9]:
df

,Console,Most Sold Game,Year of Release (Game),Units Sold (in millions)
0,PlayStation 2,Grand Theft Auto: San Andreas,2004,17.33
1,Nintendo DS,Nintendogs,2005,24.67
2,Nintendo Switch,Mario Kart 8 Deluxe,2017,52.00
3,Game Boy,Tetris,1989,35.00
4,Game Boy Color,Pokemon Gold/Silver/Crystal (1999-2000),1999,23.10
5,PlayStation 4,Grand Theft Auto V,2013,20.00
6,PlayStation,Gran Turismo,1997,10.85
7,Wii,Wii Sports,2006,82.88
8,PlayStation 3,Grand Theft Auto V,2013,21.30
9,Xbox 360,Kinect Adventures!,2010,24.00
10,Game Boy Advance,Pokemon Ruby/Sapphire/Emerald (2002-2005),2002,16.22
11,PlayStation Portable,Grand Theft Auto: Liberty City Stories,2005,7.60
12,Nintendo 3DS,Mario Kart 7,2011,20.79
13,NES/Famicom,Super Mario Bros.,1985,40.24
14,Xbox One,PlayerUnknown's Battlegrounds,2017,14.00
15,SNES/Super Famicom,Super Mario World,1990,20.60
16,Game & Watch,Ball,1980,1.10
17,Nintendo 64,Super Mario 64,1996,11.89
18,Sega Genesis/Mega Drive,Sonic the Hedgehog 2,1992,6.00
19,PlayStation 5,Marvel's Spider-Man: Miles Morales,2020,6.50
20,Atari 2600,Pac-Man,1980,7.00
21,Xbox,Halo 2,2004,8.50
22,GameCube,Super Smash Bros. Melee,2001,7.09
23,Xbox Series X/S,Call of Duty: Black Ops Cold War,2020,3.73
24,Wii U,Mario Kart 8,2014,8.45
25,PlayStation Vita,Persona 4 Golden,2012,1.50
26,Sega Master System,Alex Kidd in Miracle World,1986,1.60
27,Sega Game Gear,Sonic the Hedgehog,1991,6.24
28,PC Engine/TurboGrafx-16,Bomberman '93,1992,0.70
29,Sega Saturn,Virtual Fighter 2,1995,1.65
30,Dreamcast,Sonic Adventure,1998,2.50
31,Master System (Brazilian),Alex Kidd in Miracle World,1989,0.50
32,Dendy (Famiclone),Super Mario Bros. 3,1988,0.50
33,Super NES Classic Edition,Super Mario World,1990,5.50
34,Famicom Disk System,Super Mario Bros.,1986,6.02
35,NES Classic Edition,Super Mario Bros.,1985,2.30
36,WonderSwan,Final Fantasy,1999,1.50
37,Sega Pico,Sonic the Hedgehog's Gameworld,1994,0.50
38,Color TV-Game,Color TV-Game 6,1977,3.00
39,Intellivision,Astrosmash,1981,1.00
40,Mega Drive (Brazilian),Sonic the Hedgehog 2,1992,1.50
41,N-Gage,The Sims Bustin' Out,2004,1.00
42,Sega CD,Sonic CD,1993,1.50
43,ColecoVision,Donkey Kong,1982,1.00
44,Magnavox Odyssey,Table Tennis,1972,0.33
45,PC Engine CD-ROM,Tengai Maky?: Ziria,1989,0.80
46,Atari 7800,Pole Position II,1983,1.00
47,Atari Lynx,California Games,1989,0.50
48,Philips CD-i,The 7th Guest,1993,2.00
49,Telstar,Telstar Arcade,1977,1.00
50,Atari 5200,Super Breakout,1982,1.00

In [10]:
# It looks like the data here shows the most popular game (in terms of units sold) for each year.
# Let's make sure the year columns is unique.

len(df['Year of Release (Game)'].unique())

32

In [11]:
df.sort_values(by=['Year of Release (Game)'])

,Console,Most Sold Game,Year of Release (Game),Units Sold (in millions)
44,Magnavox Odyssey,Table Tennis,1972,0.33
49,Telstar,Telstar Arcade,1977,1.00
38,Color TV-Game,Color TV-Game 6,1977,3.00
20,Atari 2600,Pac-Man,1980,7.00
16,Game & Watch,Ball,1980,1.10
39,Intellivision,Astrosmash,1981,1.00
50,Atari 5200,Super Breakout,1982,1.00
43,ColecoVision,Donkey Kong,1982,1.00
46,Atari 7800,Pole Position II,1983,1.00
13,NES/Famicom,Super Mario Bros.,1985,40.24
35,NES Classic Edition,Super Mario Bros.,1985,2.30
34,Famicom Disk System,Super Mario Bros.,1986,6.02
26,Sega Master System,Alex Kidd in Miracle World,1986,1.60
32,Dendy (Famiclone),Super Mario Bros. 3,1988,0.50
45,PC Engine CD-ROM,Tengai Maky?: Ziria,1989,0.80
31,Master System (Brazilian),Alex Kidd in Miracle World,1989,0.50
3,Game Boy,Tetris,1989,35.00
47,Atari Lynx,California Games,1989,0.50
33,Super NES Classic Edition,Super Mario World,1990,5.50
15,SNES/Super Famicom,Super Mario World,1990,20.60
27,Sega Game Gear,Sonic the Hedgehog,1991,6.24
40,Mega Drive (Brazilian),Sonic the Hedgehog 2,1992,1.50
18,Sega Genesis/Mega Drive,Sonic the Hedgehog 2,1992,6.00
28,PC Engine/TurboGrafx-16,Bomberman '93,1992,0.70
42,Sega CD,Sonic CD,1993,1.50
48,Philips CD-i,The 7th Guest,1993,2.00
37,Sega Pico,Sonic the Hedgehog's Gameworld,1994,0.50
29,Sega Saturn,Virtual Fighter 2,1995,1.65
17,Nintendo 64,Super Mario 64,1996,11.89
6,PlayStation,Gran Turismo,1997,10.85
30,Dreamcast,Sonic Adventure,1998,2.50
4,Game Boy Color,Pokemon Gold/Silver/Crystal (1999-2000),1999,23.10
36,WonderSwan,Final Fantasy,1999,1.50
22,GameCube,Super Smash Bros. Melee,2001,7.09
10,Game Boy Advance,Pokemon Ruby/Sapphire/Emerald (2002-2005),2002,16.22
41,N-Gage,The Sims Bustin' Out,2004,1.00
0,PlayStation 2,Grand Theft Auto: San Andreas,2004,17.33
21,Xbox,Halo 2,2004,8.50
11,PlayStation Portable,Grand Theft Auto: Liberty City Stories,2005,7.60
1,Nintendo DS,Nintendogs,2005,24.67
7,Wii,Wii Sports,2006,82.88
9,Xbox 360,Kinect Adventures!,2010,24.00
12,Nintendo 3DS,Mario Kart 7,2011,20.79
25,PlayStation Vita,Persona 4 Golden,2012,1.50
8,PlayStation 3,Grand Theft Auto V,2013,21.30
5,PlayStation 4,Grand Theft Auto V,2013,20.00
24,Wii U,Mario Kart 8,2014,8.45
14,Xbox One,PlayerUnknown's Battlegrounds,2017,14.00
2,Nintendo Switch,Mario Kart 8 Deluxe,2017,52.00
23,Xbox Series X/S,Call of Duty: Black Ops Cold War,2020,3.73
19,PlayStation 5,Marvel's Spider-Man: Miles Morales,2020,6.50

In [12]:
# Let's see what are the top 10 most popular games
df.sort_values(by=['Units Sold (in millions)'], ascending=False)[0:10]

,Console,Most Sold Game,Year of Release (Game),Units Sold (in millions)
7,Wii,Wii Sports,2006,82.88
2,Nintendo Switch,Mario Kart 8 Deluxe,2017,52.00
13,NES/Famicom,Super Mario Bros.,1985,40.24
3,Game Boy,Tetris,1989,35.00
1,Nintendo DS,Nintendogs,2005,24.67
9,Xbox 360,Kinect Adventures!,2010,24.00
4,Game Boy Color,Pokemon Gold/Silver/Crystal (1999-2000),1999,23.10
8,PlayStation 3,Grand Theft Auto V,2013,21.30
12,Nintendo 3DS,Mario Kart 7,2011,20.79
15,SNES/Super Famicom,Super Mario World,1990,20.60

It is interesting to observe that eight out of the top ten most sold games were for **Nintendo**. 

![Nintendo Mario](https://assets.nintendo.eu/image/upload/f_auto/q_auto/v1641812291/MNS/dev_test_images/MyNintendo_charM02_1_R_ad-0_Large.png)

## THE END